name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set image tag
        shell: powershell
        run: |
          IMAGE="ghcr.io/Srivenkatesh03/fluidai:${{ github.sha }}"
          "IMAGE=$IMAGE" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install Python dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application validation
        shell: powershell
        run: |
          python -m compileall app

      - name: Login to GHCR
        shell: powershell
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t $env:IMAGE .

      - name: Push Docker image
        shell: powershell
        run: |
          docker push $env:IMAGE

      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/postgres-pvc.yaml
          kubectl apply -f k8s/postgres.yaml
          kubectl apply -f k8s/postgres-service.yaml

          kubectl set image deployment/backend `
            backend=$env:IMAGE `
            -n fluid-ai

          kubectl apply -f k8s/backend-service.yaml

      - name: Wait for rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/backend `
            -n fluid-ai `
            --timeout=120s

      - name: Verify deployment
        shell: powershell
        run: |
          kubectl get pods -n fluid-ai
          kubectl get svc -n fluid-ai
          kubectl get deployment -n fluid-ai